const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257
  },
  events: [
    {
      created: 1579613161000,
      duration: 28800000,
      id: '268084088',
      name: 'Mindset Booster für Gründer*innen in der ersten Phase',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1583568000000,
      local_date: '2020-03-07',
      local_time: '09:00',
      updated: 1579613490000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      group: {
        created: 1544797330000,
        name: 'Founders@UniBw - Entrepreneurship an der UniBw M',
        id: 30706739,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Founders-unibw',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Founders-unibw/events/268084088/',
      description: '<p>09:00 Organisatorisches, Tagesablauf, Kennenlernen</p> <p>09:30 Moments of Excellence &amp; Misery<br/>Erkenne deine Muster und lerne danach zu<br/>handeln</p> <p>10:30 Ski Session I<br/>Die Ski Sessions sind ein Mix aus freiem<br/>Fahren, Austausch mit anderen Gründern,<br/>Reflexion von Coaching Interventionen und<br/>Spaß haben.</p> <p>13:00 Mittagspause<br/>Die Mittagspause nutzt du, um dich zu<br/>erholen, deine Energiespeicher wieder<br/>aufzufüllen und dich mit den anderen<br/>Gründern auszutauschen.</p> <p>13:30 Deine Einzigartigkeit als Gründer<br/>Finde heraus, was dich als Gründer einzigartig<br/>macht und wo du Unterstützung brauchst.</p> <p>14:30 Ski Session II<br/>Die Ski Sessions sind ein Mix aus freiem Fahren,<br/>Austausch mit anderen Gründern, Reflexion<br/>von Coaching Interventionen und Spaß haben.</p> <p>16:30 Abschlussreflexion &amp; Gemeinsame letzte<br/>Abfahrt</p> <p>17:00 Aprés Ski, Ausklang und Abreise</p> <p>Ort: Zillertal, genauere Angaben folgen<br/>Kosten: Kai Gausmann ist ausgebildeter Life &amp; Business<br/>Coach sowie lizensierter Skilehrer. Coaching &amp;<br/>Skibegleitung sind an diesem Tag kostenlos</p> <p>Anmeldung: Du zahlst lediglich die normalen Kosten eines<br/>Skitages (Anreise, Skipass, Verpflegung, Material,<br/>etc.)<br/>Verbindliche Anmeldungen bis spätestens<br/>[masked] an [masked] . Die<br/>Anmeldung wird nur bei Zahlung einer<br/>Buchungspauschale von 20€ wirksam. Das Geld<br/>wird als Anzahlung für den Skipass eingesetzt. Nur<br/>bei Nichterscheinen zum Skitag verfällt der Betrag<br/>und wird nicht zurück erstattet.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1578387141000,
      duration: 7200000,
      id: '267713399',
      name: 'TELT – Datentransfer von modernen Cloud-Anwendungen in ein Data Warehouse',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581962400000,
      local_date: '2020-02-17',
      local_time: '19:00',
      updated: 1580716471000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 25,
      venue: {
        id: 26674415,
        name: 'WERK3',
        lat: 48.12529373168945,
        lon: 11.605690002441406,
        repinned: true,
        address_1: 'WERKSVIERTEL-MITTE',
        address_2: 'c/o attempto',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1549895569000,
        name: 'Smart Datalytics München',
        id: 31139636,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'meetup-group-ivvLeeEO',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/meetup-group-ivvLeeEO/events/267713399/',
      description: '<p>Datenpipelinedienste in der Cloud verfügen aktuell noch über einen deutlich reduzierten Funktionsumfang gegenüber etablierten ETL-Lösungen. Wir stellen mit TELT unseren Ansatz vor, um den Datentransfer auch mit komplexen Transformationen und Datenaufbereitungen von der Anwendung bis zur Reporting- und Analyseplattform komplett cloudbasiert abzubilden. In der anschließenden Diskussion möchten wir TELT und klassische on-premise Systeme inklusive einer aufwändigen ETL-Strecke gegenüberstellen.</p> <p>TELT – Shipping data from modern cloud applications to Data Warehouses<br/>Data-pipeline services in Clouds are yet much more limited in functionality and flexibility in comparison to traditional on-premise tools for ETL. We therefore will present TELT, our approach to organize data in Clouds from user entry to reporting and analytical platforms, including complex transformation and cleaning. In subsequent discussion, we would like to juxtapose TELT and on-premise systems including an exhaustive ETL.</p> <p>Smart Datalytics:<br/>Die regelmäßig stattfindende Veranstaltung bietet ein offenes Forum für den Austausch von Ideen, Meinungen und Expertisen zu den weitgefassten Themenkreisen Analytics, Business Intelligence und Big Data. Nach dem Impulsvortrag geht es in ein Open Space Format über, bei dem sich jeder Teilnehmer einbringen kann. Wie immer sorgen wir für die Verpflegung!</p> <p>Wo: WERK3, WERKSVIERTEL-MITTE c/o attempto, 2. Stock, Atelierstraße 18, 81671 München<br/>Wann: Montag, 17. Februar 2020 um 19:00 Uhr<br/>Organisiert von: tekaris GmbH</p> <p>Die Smart Datalytics Veranstaltungsreihe ist initiiert von: atlantis media &amp; ERGON Datenprojekte</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1578932249000,
      duration: 7200000,
      fee: {
        accepts: 'paypal',
        amount: 5,
        currency: 'EUR',
        description: '',
        label: 'Price',
        required: true
      },
      id: '267879924',
      name: 'Workshop: Character Development',
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582369200000,
      local_date: '2020-02-22',
      local_time: '12:00',
      updated: 1578932249000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      group: {
        created: 1540275214000,
        name: 'Happy Writing: Munich',
        id: 30375868,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Happy-Writing-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Happy-Writing-Munich/events/267879924/',
      description: '<p>Are you struggling with your characters? Not enough life? Feeling one dimensional? Not even sure where to start?<br/>We\'re going to workshop our way through character development. For this class, we will primarily be focusing on our main character\'s creation or strengthening.<br/>We will spend quite a lot of time figuring out exactly who they are, what they want, and what they need. All participants will get a character development workbook to go through the day of the event.<br/>Event location will be determined and announced one week before the event due to group size.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1580396975000,
      duration: 2700000,
      id: '268321786',
      name: 'Product Management Live Chat by Sandboxx Chief Product Officer',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1586888100000,
      local_date: '2020-04-14',
      local_time: '20:15',
      updated: 1580397318000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      group: {
        created: 1570531441000,
        name: 'Product School Munich',
        id: 32863959,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Product-School-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Product-School-Munich/events/268321786/',
      description: 'Hello',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1579639805000,
      duration: 7200000,
      id: '268094012',
      name: 'Open Mic night - Live music unplugged',
      rsvp_limit: 50,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582221600000,
      local_date: '2020-02-20',
      local_time: '19:00',
      updated: 1580296405000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 33,
      venue: {
        id: 26835674,
        name: 'Das Provisorium- Kunstbar Und Lesesaal',
        lat: 48.12763214111328,
        lon: 11.601123809814453,
        repinned: false,
        address_1: 'Gravelottestraße 7',
        address_2: '81667 ',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1579639457000,
        name: 'Open Mic - Live Music Unplugged',
        id: 33228840,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Open-Mic-Live-music-unplugged',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Open-Mic-Live-music-unplugged/events/268094012/',
      description: '<p>Hey people,</p> <p>We are organizing an Open Mic event at Das Provisorium on[masked].</p> <p>We\'re trying to create an event where hobby musicians/musically inclined people can meet, hang out, find collaborators, organize jam sessions, or just chill and grab a beer and enjoy some performances. You get the vibe. In general just a fun event for people who have/want music in their lives.</p> <p>If this sounds like fun/your kind of thing, you can drop us a text to get the technical details and more information on time slot.</p> <p>If this does sounds like your thing, but you\'re a vocalist looking for an instrumentalist or vice versa, just shoot a text, and I\'m sure we can work something out.</p> <p>There no genre, so feel free to come play whatever songs you like.</p> <p>Looking forward to your responses</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1580821390000,
      duration: 7200000,
      id: '268448587',
      name: 'Elementor MeetUp München - What the fuck is Crocoblock?',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1583258400000,
      local_date: '2020-03-03',
      local_time: '19:00',
      updated: 1580837169000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26638286,
        name: 'Heinrich Marketing GmbH',
        lat: 48.14986038208008,
        lon: 11.549469947814941,
        repinned: true,
        address_1: 'Nymphenburger Str. 58',
        address_2: 'Hinterhof, rechts',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1549966106000,
        name: 'Elementor München',
        id: 31146435,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Muenchen-Elementor-Meetup',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Muenchen-Elementor-Meetup/events/268448587/',
      description: '<p>Crocoblock ist eine Suite von mittlerweile 17 Plugins der Ukrainischen Softwareschmiede Zemez. Crocoblock setzt auf Elementor auf und erweitert es mit einer Vielzahl an Widgets und Funktionalitäten, wie z.B. dynamische Darstellung von Inhalten, Mega Menü, visuelle Effekte, Style Manager, Filter- und Suchfunktionen, Addons für WooCommerce, Produktgalerien und vieles mehr.</p> <p>An einem Abend können wir nicht alle Möglichkeiten von Crocoblock darstellen, aber Helmut Göbel gibt ein Überblick und geht auf einige Widgets und Funktionen detaillierter ein.</p> <p>Dieses Meetup ist für jeden interessant, der keine 08/15-Webseite haben möchte, sondern in Design und/oder Funktion gerne etwas außergewöhnliches und überdurchschnittliches haben möchte.</p> <p>Hinweise:<br/>1. Wir sind zu Gast in der Agentur von Andreas Heinrich. Der Platz ist eingeschränkt. Deswegen bitte schnellstmöglich anmelden.<br/>2. Zum Netzwerken ist es sinnvoll, Visitenkarten mitzubringen und sich gegenseitig auszuhändigen. Das hilft, langfristig in Kontakt zu bleiben.<br/>3. In der Umgebung gibt es kaum Parkplätze. Es wird dringend empfohlen, den ÖPNV zu nutzen.</p> <p>Wir gehen anschließend in das Restaurant Trattoria Sankt Benno (Loristraße 14), wenige Schritte entfernt. Dort gibt es weiter Gelegenheit Fragen zu stellen und sich zum Thema Elementor auszutauschen. Wer mitkommen will, ist herzlich eingeladen.</p> ',
      how_to_find_us: 'Firma Heinrich Marketing befindet sich im Rückgebäude der Nymphenburger Str. 58, ca. 250 Meter von der U-Bahn-Station Maillinger Str. (U 1) entfernt. Es wird empfohlen, nicht mit dem Auto zu kommen. Freie Parkplätze gibt es in der Umgebung kaum.',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1580468242000,
      duration: 10800000,
      id: '268348914',
      name: 'Wine and Cheese day',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582221600000,
      local_date: '2020-02-20',
      local_time: '19:00',
      updated: 1580468242000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 13,
      group: {
        created: 1434007980000,
        name: 'München Wine Tasting Club',
        id: 18664929,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Wine-Tasting-Club',
        who: 'München Wine Tasters',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munchen-Wine-Tasting-Club/events/268348914/',
      description: '<p>Wine and Cheese such a wonderful reason to get together.</p> <p>Once a month, we are meeting to drink wine with great pairing cheeses.<br/>With every sort of wine, you will get a chance to try a pairing cheese.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1579782271000,
      duration: 7200000,
      fee: {
        accepts: 'cash',
        amount: 10,
        currency: 'EUR',
        description: '',
        label: 'Price',
        required: false
      },
      id: '268138985',
      name: 'How To Identify Your Limiting Beliefs And Get Rid Of Them - With Max LEONE',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1584469800000,
      local_date: '2020-03-17',
      local_time: '19:30',
      updated: 1580236895000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 18,
      group: {
        created: 1575279213000,
        name: 'How To Develop Your Full Potential (Munich)',
        id: 33066592,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Powerful-Minds-Munich',
        who: 'Powerful Minds',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Powerful-Minds-Munich/events/268138985/',
      description: 'Hello',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1578127407000,
      duration: 7200000,
      id: 'tsjmnrybcfbhc',
      name: 'Restaurant hopping',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1585159200000,
      local_date: '2020-03-25',
      local_time: '19:00',
      updated: 1580296762000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      group: {
        created: 1578072802000,
        name: 'Foodtour - Foodies are welcome to hop through restaurants',
        id: 33160683,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Foodtour-Foodies-are-welcome-to-hop-through-restaurants',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Foodtour-Foodies-are-welcome-to-hop-through-restaurants/events/tsjmnrybcfbhc/',
      description: '<p>If you cannot attend, please opt out so others get a chance to meetup.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1578860183000,
      duration: 5400000,
      id: '267860450',
      name: '#geomobMUC I 2020, Safety & Security',
      rsvp_limit: 150,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1585243800000,
      local_date: '2020-03-26',
      local_time: '18:30',
      updated: 1579198260000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 20,
      group: {
        created: 1551172295000,
        name: 'Geomob Munich #geomobMUC',
        id: 31257448,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Geomob-Munich-geomobMUC',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Geomob-Munich-geomobMUC/events/267860450/',
      description: 'Hello',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1571223250000,
      duration: 7200000,
      id: '265709123',
      name: 'Wow yes Early Stage Startups Pitchnight #1 - München',
      rsvp_limit: 200,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1583949600000,
      local_date: '2020-03-11',
      local_time: '19:00',
      updated: 1576671092000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 140,
      group: {
        created: 1571221326000,
        name: 'Wow Yes Startups - München',
        id: 32898396,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'wow-yes-Startups-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/wow-yes-Startups-Munchen/events/265709123/',
      description: 'Hello',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1580738783000,
      duration: 7200000,
      fee: {
        accepts: 'paypal',
        amount: 10,
        currency: 'EUR',
        description: '',
        label: 'Price',
        required: true
      },
      id: '268422505',
      name: 'Workshop: Social Media for Authors',
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1584183600000,
      local_date: '2020-03-14',
      local_time: '12:00',
      updated: 1580738783000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      group: {
        created: 1540275214000,
        name: 'Happy Writing: Munich',
        id: 30375868,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Happy-Writing-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Happy-Writing-Munich/events/268422505/',
      description: '<p>If you\'re in the modern publishing landscape, you might see social media as a barrier. Some agents require a specific following number to even look at your work. While it\'s not for everyone, and certainly not everyone needs to be strong on social media, if this is an area you want to know more about, we\'re here to teach you!</p> <p>This workshop will be led by Dionne. In addition to teaching Social Media Marketing at EU Business School, Dionne is a certified Goal Achievement Life Coach. She actively coaches authors in building their platform and fine tuning their socials, and has helped build some of the largest Twitter tags and very successful author YouTube accounts with her clients.</p> <p>Location will be announced closer to the workshop depending on how many people sign up.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1536494061000,
      duration: 16200000,
      id: 'snxjfqybcdbnb',
      name: 'Meeple Monday',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581355800000,
      local_date: '2020-02-10',
      local_time: '18:30',
      rsvp_open_offset: 'PT186H30M',
      rsvp_close_offset: 'PT30M',
      updated: 1536494061000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 20,
      venue: {
        id: 25689781,
        name: 'Kulturladen Westend',
        lat: 48.134117126464844,
        lon: 11.541715621948242,
        repinned: true,
        address_1: 'Ligsalzstrasse 44',
        city: 'München ',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1449524089000,
        name: 'Munich Boardgame Meetup',
        id: 19191650,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Boardgame-Meetup',
        who: 'Boardgamers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Boardgame-Meetup/events/snxjfqybcdbnb/',
      description: '<p>Every second Monday of the month. Location right next to U-Bahn Schwanthalerhöhe. As always: games are usually English or language neutral. There is a fridge with drinks for 1,50 each. Please bring your favorite Games or just join. RSVP opens one week before the event.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1562151747000,
      duration: 169200000,
      id: '262837309',
      name: 'Campus Hackathon München 2020',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1587142800000,
      local_date: '2020-04-17',
      local_time: '19:00',
      updated: 1562151747000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      group: {
        created: 1501244830000,
        name: 'Tech_Hub München',
        id: 25186228,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Tech_Hub-Munchen',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Tech_Hub-Munchen/events/262837309/',
      description: 'Hello',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1579526600000,
      duration: 10800000,
      id: '268058147',
      name: 'Swift Meetup Munich #21',
      rsvp_limit: 60,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582135200000,
      local_date: '2020-02-19',
      local_time: '19:00',
      updated: 1579527305000,
      utc_offset: 3600000,
      waitlist_count: 29,
      yes_rsvp_count: 60,
      group: {
        created: 1423676119000,
        name: 'Swift Meetup Munich',
        id: 18428182,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Swift-Meetup-Munich',
        who: 'Swift Developers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Swift-Meetup-Munich/events/268058147/',
      description: 'Hello',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1579774150000,
      duration: 10800000,
      id: '268137509',
      name: 'Offene Männergruppe | No More Mr Nice Guy',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581012000000,
      local_date: '2020-02-06',
      local_time: '19:00',
      updated: 1579774395000,
      utc_offset: 3600000,
      waitlist_count: 3,
      yes_rsvp_count: 20,
      venue: {
        id: 26700573,
        name: 'freiraum München ',
        lat: 48.16446304321289,
        lon: 11.561508178710938,
        repinned: true,
        address_1: 'Saarstr. 5',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1440924660000,
        name: 'No More Mr. Nice Guy Männergruppe München',
        id: 18881708,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'No-More-Mr-Nice-Guy-Muenchen',
        who: 'Männer',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/No-More-Mr-Nice-Guy-Muenchen/events/268137509/',
      description: 'Hello ',
      how_to_find_us: '1. Stock',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1579702329000,
      duration: 7200000,
      id: '268111707',
      name: 'How To Design Awesome CSS Components with Le Wagon',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582651800000,
      local_date: '2020-02-25',
      local_time: '18:30',
      updated: 1579702329000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      group: {
        created: 1574935324000,
        name: 'Le Wagon Munich - Coding Bootcamp',
        id: 33056128,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Le-Wagon-Munich',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Le-Wagon-Munich/events/268111707/',
      description: 'Hello ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1564129835000,
      duration: 7200000,
      id: 'qbmqfrybcdblb',
      name: 'Shut Up & Write!™ Munich',
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581150600000,
      local_date: '2020-02-08',
      local_time: '09:30',
      rsvp_open_offset: 'PT163H30M',
      updated: 1564129835000,
      utc_offset: 3600000,
      waitlist_count: 14,
      yes_rsvp_count: 15,
      venue: {
        id: 25966475,
        name: 'Bellevue München',
        lat: 48.160736083984375,
        lon: 11.563915252685547,
        repinned: false,
        address_1: 'Schleißheimer Str. 142a',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1532540208000,
        name: 'Shut Up & Write!® Munich',
        id: 29351354,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'shutupandwritemunich',
        who: 'Writers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/shutupandwritemunich/events/qbmqfrybcdblb/',
      description: '<p>Join us for an hour of writing! We’ve discovered that it’s strikingly helpful to write with other writers. See if it’s true for you at 09:30 on Saturday.</p> <p>Be it a book, blog, script, essay, dissertation, resume, melody, poem or just plain work stuff, you are invited to write it with us. No one will see what you\'ve written or give you unsolicited advice. Instead of just thinking about writing, come and get some real writing done.<br/>SCHEDULE:<br/>09:30 - SESSION 1: quick intros.<br/>09:45 - timer starts: write for 1 hour.<br/>10:45 - chat / take off / keep writing for another timed hour (starting at ~11:15).</p> <p>OPTIONAL SOCIALIZING happens after we\'re done with the first/second writing hour. Writing is very solitary. Connecting (and sometimes even commiserating) with other writers is a cool thing.<br/>BEING LATE IS OKAY: just show up and get settled, then check-in with me after the session. (I’ll be the person with the Shut Up &amp; Write! sign.) If you were on time, please be willing to make room for the friendly latecomer.<br/>Happy writing and I look forward to seeing you!</p> <p>What Should I Bring?<br/>Whatever you need to be able to write!<br/>Bring earbuds/earplugs if you want to block the cafe’s overhead music or the occasional conversation by other patrons.<br/>There should be enough sockets to charge your devices, but make sure to charge them just in case! :)</p> <p>Other Important Details:<br/>GUIDELINES: Please thank our hosts by purchasing something.<br/>FUTURE LOCATIONS: If you have ideas about where and when we should meet, please share them! :)<br/>If you\'re on the waiting list, but still really really want to come, feel free to drop by — but in case we end up being too large of a group to manage, or we don\'t find enough free seats, the priority is on the folks with the \'going\' RSVPs!</p> ',
      how_to_find_us: 'Look for the Shut up & Write! sign or ask for Arnaud ',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1580133139000,
      duration: 7200000,
      id: '268237268',
      name: 'Brothers Karamazov, 1st half, -- Second meeting',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581012900000,
      local_date: '2020-02-06',
      local_time: '19:15',
      updated: 1580133139000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      group: {
        created: 1444135614000,
        name: 'Munich reading circle / München Lesekreis Meetup',
        id: 19001239,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Lesekreis-Meetup',
        who: 'Bücherliebhaber',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munchen-Lesekreis-Meetup/events/268237268/',
      description: '<p>A second round of the first half of the book. If possible, read through the Grand Inquisitor essay (end of part II -- the book is written in IV parts).</p> <p>If you can\'t get through the whole first half, do read hte Grand inquisitor essay on it\'s own to be prepared for the discussion.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1579209196000,
      duration: 12600000,
      id: '267972434',
      name: 'Developing with Machine Learning with or without expertise',
      rsvp_limit: 200,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581442200000,
      local_date: '2020-02-11',
      local_time: '18:30',
      rsvp_close_offset: 'PT24H',
      updated: 1579270643000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 163,
      venue: {
        id: 26588465,
        name: 'STYLIGHT HQ',
        lat: 48.1500244140625,
        lon: 11.546462059020996,
        repinned: true,
        address_1: 'Nymphenburgerstr. 86',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1478266159000,
        name: 'GDG Cloud Munich',
        id: 21038385,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'GDG-cloud-munich',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/GDG-cloud-munich/events/267972434/',
      description: '<p>Let\'s kick start new journey into 2020 with our great friends Stylight HQ.</p> <p>⏰ Schedule:<br/>• 18:30 - 18:50: 🍕Doors open<br/>• 18:50 - 19:00: 📢 Announcements<br/>• 🎤 Laurent Picard<br/>Building smarter solutions with no expertise in machine learning.<br/>• 🎤Zack Akil<br/>Safer cycling with an Edge TPU watching your back<br/>• 🎤Polong Lin<br/>Machine learning at scale with BigQuery, Colab and AI Platform notebooks on Google Cloud<br/>• 21:30 - 22:00: Networking</p> <p>🔘 Laurent Picard – Building smarter solutions with no expertise in machine learning.</p> <p>ML? API? AutoML? What can we build in only a few hours or days? In this session, we\'ll see how to benefit from existing ML models and how to create a custom model with AutoML techniques. We’ll also be active players of a live demo, so don\'t put your smartphone on airplane mode!</p> <p>Laurent is a developer passionate about software, hardware, science, and everything shaping the future. He works for Google Cloud where he enjoys exploring and sharing what\'s possible. In a prior life, he pioneered the ebook industry, co-created the 1st European ebook reader, and co-founded Bookeen.</p> <p>🔘 Zack Akil – Safer cycling with an Edge TPU watching your back</p> <p>Cycling in central London is an extreme sport! To give me the competitive edge I\'ve built a machine vision model that runs on an Edge TPU that keeps me informed about the dangerous vehicles that are behind me in blistering real time. I\'ll show you the end-to-end process of developing and deploying the model to the recently released Edge TPU hardware from Google.</p> <p>Zack is a developer advocate for Cloud Machine Learning at Google. When he’s not teaching machine learning at Google, he likes to teach machine learning at his hands-on data science meetup, Central London Data Science Project Nights. Although he works in the cloud, most of his hobby projects look at different ways you can embed machine learning into low-power devices like Raspberry Pis and Arduinos. He also likes to have a bit of banter with his mixed tag rugby teams.</p> <p>🔘 Polong Lin – Machine learning at scale with BigQuery, Colab and AI Platform notebooks on Google Cloud</p> <p>How can data scientists scale their machine learning pipelines with minimal data engineering overhead? Polong Lin (Developer Advocate, Google) will discuss how BigQuery ML, Colab and AI Platform can be used together to help businesses accelerate their growth with data.</p> <p>Polong is a Developer Advocate at Google, based in London, UK, with a focus on data science and machine learning. Due to his background in psychology, Polong gets particularly excited about data science projects at the intersection of data science and human behaviour.</p> <p>👀🌟 We are looking forward for next events, if you have topic suggestion, or want to talk we are open for speakers and sponsors 🤝</p> <p>See you at the meetup!</p> <p>-- Yevgen and Mario</p> ',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1580397803000,
      duration: 1800000,
      id: '268321996',
      name: 'Webinar: Step Up and Lead by Google Product Lead',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1585247400000,
      local_date: '2020-03-26',
      local_time: '19:30',
      updated: 1580398028000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      group: {
        created: 1570531441000,
        name: 'Product School Munich',
        id: 32863959,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Product-School-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Product-School-Munich/events/268321996/',
      description: 'Hello',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1575369043000,
      duration: 28800000,
      id: '266914908',
      name: 'Storytelling Innovation Workshop',
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1580979600000,
      local_date: '2020-02-06',
      local_time: '10:00',
      updated: 1580468259000,
      utc_offset: 3600000,
      waitlist_count: 2,
      yes_rsvp_count: 15,
      venue: {
        id: 26756901,
        name: 'MUCBOOK CLUBHAUS',
        lat: 48.138675689697266,
        lon: 11.561399459838867,
        repinned: true,
        address_1: 'Schillerstr. 3a (Hinterhof)',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1574928701000,
        name: 'Structured Creativity - Kreativ- und Innovationsmethoden',
        id: 33055949,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Structured-Creativity-Kreativ-und-Innovationsmethoden',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Structured-Creativity-Kreativ-und-Innovationsmethoden/events/266914908/',
      description: 'Hello ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1578563403000,
      duration: 9000000,
      id: '267773569',
      name: 'Kickoff Julia User Group Munich',
      rsvp_limit: 40,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1580923800000,
      local_date: '2020-02-05',
      local_time: '18:30',
      updated: 1580637225000,
      utc_offset: 3600000,
      waitlist_count: 10,
      yes_rsvp_count: 40,
      venue: {
        id: 26841597,
        name: 'Machine Learning Reply',
        lat: 48.14474868774414,
        lon: 11.538175582885742,
        repinned: false,
        address_1: 'Luise Ullrich Straße 14',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1578504145000,
        name: 'Julia User Group Munich',
        id: 33180408,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Julia-User-Group-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Julia-User-Group-Munich/events/267773569/',
      description: 'Hello ',
      how_to_find_us: 'We gather in the ground floor of the Nove office and go to the special area called Solar. For those coming late, just ask at the reception in the ground floor and they will lead you to the Solar area.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1578127407000,
      duration: 7200000,
      id: 'tsjmnrybcdbjc',
      name: 'Restaurant hopping',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582740000000,
      local_date: '2020-02-26',
      local_time: '19:00',
      updated: 1580296761000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 9,
      group: {
        created: 1578072802000,
        name: 'Foodtour - Foodies are welcome to hop through restaurants',
        id: 33160683,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Foodtour-Foodies-are-welcome-to-hop-through-restaurants',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Foodtour-Foodies-are-welcome-to-hop-through-restaurants/events/tsjmnrybcdbjc/',
      description: '<p>If you cannot attend, please opt out so others get a chance to meetup.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1576311322000,
      duration: 7200000,
      id: '267182421',
      name: 'Andrew Pruski - Chaos Engineering for SQL Server',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1587661200000,
      local_date: '2020-04-23',
      local_time: '19:00',
      updated: 1578403978000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      group: {
        created: 1462514436000,
        name: 'Microsoft Data Platform Community - PASS Deutschland e.V.',
        id: 19921609,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'pass-bayern',
        who: 'Data Monsters',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/pass-bayern/events/267182421/',
      description: '<p>In this session we will explore the concept of Chaos Engineering, its core concepts, and how it has been implemented at various companies.</p> <p>Then we\'ll look at how it can be implemented with regard to SQL Server. SQL has various different high availability solutions but can you be sure that they\'ll react as expected to a real world issue? Has your HA architecture only ever been tested in a planned maintenance window?</p> <p>We\'ll also have some fun by looking at KubeInvaders, a chaos engineering tool for Kubernetes...using Space Invaders!</p> <p>This session is for SQL Server DBAs and Developers who want to know how Chaos Engineering works and want to learn its main principles.</p> <p>Andrew Pruski</p> <p>SQL Server DBA originally from Wales but now exploring Ireland</p> <p>I\'m a SQL Server DBA and Microsoft Data Platform MVP, you can find me on twitter @dbafromthecold and blogging at dbafromthecold.com</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1566330486000,
      duration: 738000000,
      id: '264167492',
      name: 'XC ski holiday 2020: Geilo, Norway',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1584770400000,
      local_date: '2020-03-21',
      local_time: '07:00',
      updated: 1579374006000,
      utc_offset: 3600000,
      waitlist_count: 8,
      yes_rsvp_count: 11,
      group: {
        created: 1444594505000,
        name: 'Munich Cross-Country Skiers',
        id: 19017438,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'munichXC',
        who: 'Cross-country skiers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/munichXC/events/264167492/',
      description: 'Hello ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1580680570000,
      duration: 5400000,
      id: '268409411',
      name: 'Co-Lunch: Neue Kontakte in der Mittagspause',
      rsvp_limit: 17,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581679800000,
      local_date: '2020-02-14',
      local_time: '12:30',
      updated: 1580680570000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26822176,
        name: 'togather',
        lat: 48.137943267822266,
        lon: 11.543676376342773,
        repinned: true,
        address_1: 'Schwanthalerstraße 160',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1538836714000,
        name: 'Co-Dining: inspirierender Austausch u. Netzwerken beim Essen',
        id: 30090989,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Co-Dining',
        who: 'Netzwerkerinnen und Netzwerker',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Co-Dining/events/268409411/',
      description: '<p>WAS IST CO-LUNCH</p> <p>Das Co-Lunch ist wie immer dazu da, die Mittagspause zu nutzen um neue Leute kennen zu lernen und beruflich oder privat zu Netzwerken. Hol dir frische Motivation und Inspiration in deiner Lunch Break.<br/>Wonach auch immer dir an diesem Tag, zu dieser Stunde ist, sei ruhig, sei laut, erzähle oder höre zu. Komm aus dich raus oder genieße dein Essen an der großen Tafel. Alles darf sein. Jeder ist willkommen. Sei neugierig, wer heute mit am Tisch sitzt.</p> <p>Jeder kommt für den eigenen Verzehr auf.</p> <p>Bitte sagt ab, falls ihr es nicht schafft zu kommen.</p> <p>-------------------------------------english------------------------------------<br/>Why not using the lunch break to meet new inspiring people, to make new business contacts and broaden your network.<br/>I like to meet others who appreciate the idea of socializing, networking and having a quality time at lunch. A perfect lunch break for me is an empowering break in the middle of the day, which gives me energy and motivation for the second half of the day. Lets have lunch together.</p> <p>Agenda:<br/>There is no such thing like an agenda. Everbody will have the opportunitiy to introduce himself. There should be room to embrace yourself, to listen to others, to ask and to answer. Be kind to another, get inspired and motivate each other for a better life.</p> <p>Looking forward to see you soon.</p> <p>1st note: Kindly only sign up, if you can really make it. Please cancel your reservation if you cannot appear.</p> <p>2nd note: Everbody pays for his or her own consumption.</p> <p>Bis bald and see you soon,<br/>Eure Sarah</p> ',
      how_to_find_us: 'Meetup Tisch in der Mitte',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1576311289000,
      duration: 7200000,
      id: '267182416',
      name: 'Data Engineering Pattern in der Data Factory - Stefan Kirner',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1584036000000,
      local_date: '2020-03-12',
      local_time: '19:00',
      updated: 1576493120000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 26,
      group: {
        created: 1462514436000,
        name: 'Microsoft Data Platform Community - PASS Deutschland e.V.',
        id: 19921609,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'pass-bayern',
        who: 'Data Monsters',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/pass-bayern/events/267182416/',
      description: '<p>Abstract and location will come soon!</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1579090013000,
      duration: 7200000,
      id: '267931462',
      name: 'Social Media im Recruiting: Das sagt ein Rechtsanwalt',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1584639000000,
      local_date: '2020-03-19',
      local_time: '18:30',
      updated: 1580131313000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      group: {
        created: 1534928823000,
        name: 'We Hustle in Recruiting Munich',
        id: 29593797,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'We-Hustle-in-Recruiting-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/We-Hustle-in-Recruiting-Munich/events/267931462/',
      description: 'Hello ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1580151057000,
      duration: 10800000,
      id: 'kqblnrybcdbpb',
      name: 'Shut Up & Write!™ Munich',
      rsvp_limit: 12,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581440400000,
      local_date: '2020-02-11',
      local_time: '18:00',
      rsvp_open_offset: 'PT168H',
      updated: 1580151101000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      venue: {
        id: 25711269,
        name: 'Cotidiano Promenadeplatz',
        lat: 48.14008331298828,
        lon: 11.569615364074707,
        repinned: true,
        address_1: 'Maxburgstraße 4',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1532540208000,
        name: 'Shut Up & Write!® Munich',
        id: 29351354,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'shutupandwritemunich',
        who: 'Writers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/shutupandwritemunich/events/kqblnrybcdbpb/',
      description: '<p>Join us for an hour of writing! We’ve discovered that it’s strikingly helpful to write with other writers.</p> <p>Be it a book, blog, script, essay, dissertation, resume, melody, poem or just plain work stuff, you are invited to write it with us. No one will see what you\'ve written or give you unsolicited advice. Instead of just thinking about writing, come and get some real writing done.<br/>SCHEDULE (roughly):</p> <p>18:15 - SESSION 1: quick intros.<br/>18:20 - timer starts: write for 1 hour.<br/>19:20 - chat / take off / keep writing for another timed hour (starting at ~19:45).</p> <p>OPTIONAL SOCIALIZING happens after we\'re done with the first/second writing hour. Writing is very solitary. Connecting (and sometimes even commiserating) with other writers is a cool thing.<br/>BEING LATE IS OKAY: just show up and get settled, then check-in with me after the session. (I’ll be the person with the Shut Up &amp; Write! sign.) If you were on time, please be willing to make room for the friendly latecomer.<br/>Happy writing and I look forward to seeing you!</p> <p>What Should I Bring?<br/>Whatever you need to be able to write!<br/>Bring earbuds/earplugs if you want to block the cafe’s overhead music or the occasional conversation by other patrons.<br/>There should be enough sockets to charge your devices, but make sure to charge them just in case! :)</p> <p>Other Important Details:<br/>GUIDELINES: Please thank our hosts by purchasing something.<br/>FUTURE LOCATIONS: If you have ideas about where and when we should meet, please share them! :)<br/>If you\'re on the waiting list, but still really really want to come, feel free to drop by — but in case we end up being too large of a group to manage, or we don\'t find enough free seats, the priority is on the folks with the \'going\' RSVPs!</p> ',
      how_to_find_us: 'Reservations under Spiegel',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1580252470000,
      duration: 5400000,
      id: '268278466',
      name: 'Co-Lunch: Neue Kontakte in der Mittagspause',
      rsvp_limit: 14,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1580902200000,
      local_date: '2020-02-05',
      local_time: '12:30',
      updated: 1580252470000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 10,
      venue: {
        id: 26822176,
        name: 'togather',
        lat: 48.137943267822266,
        lon: 11.543676376342773,
        repinned: true,
        address_1: 'Schwanthalerstraße 160',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1538836714000,
        name: 'Co-Dining: inspirierender Austausch u. Netzwerken beim Essen',
        id: 30090989,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Co-Dining',
        who: 'Netzwerkerinnen und Netzwerker',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Co-Dining/events/268278466/',
      description: '<p>Liebe Co-Lunch Freund*innen,<br/>WAS IST CO-LUNCH</p> <p>Das Co-Lunch ist wie immer dazu da, die Mittagspause zu nutzen um neue Leute kennen zu lernen und beruflich oder privat zu Netzwerken. Hol dir frische Motivation und Inspiration in deiner Lunch Break.<br/>Wonach auch immer dir an diesem Tag, zu dieser Stunde ist, sei ruhig, sei laut, erzähle oder höre zu. Komm aus dich raus oder genieße dein Essen an der großen Tafel. Alles darf sein. Jeder ist willkommen. Sei neugierig, wer heute mit am Tisch sitzt.</p> <p>Jeder kommt für den eigenen Verzehr auf.</p> <p>Bitte sagt ab, falls ihr es nicht schafft zu kommen.</p> <p>-------------------------------------english------------------------------------<br/>Why not using the lunch break to meet new inspiring people, to make new business contacts and broaden your network.<br/>I like to meet others who appreciate the idea of socializing, networking and having a quality time at lunch. A perfect lunch break for me is an empowering break in the middle of the day, which gives me energy and motivation for the second half of the day. Lets have lunch together.</p> <p>Agenda:<br/>There is no such thing like an agenda. Everbody will have the opportunitiy to introduce himself. There should be room to embrace yourself, to listen to others, to ask and to answer. Be kind to another, get inspired and motivate each other for a better life.</p> <p>Looking forward to see you soon.</p> <p>1st note: Kindly only sign up, if you can really make it. Please cancel your reservation if you cannot appear.</p> <p>2nd note: Everbody pays for his or her own consumption.</p> <p>Bis bald and see you soon,<br/>Eure Sarah</p> ',
      how_to_find_us: 'Meetup Tisch',
      visibility: 'public',
      member_pay_fee: false
    }
  ]
};
export { mockEvents };
